### PR TITLE
Restore additional tests

### PR DESCRIPTION
**Pull request by ibacher**

### CODE REVIEW

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors ping

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors try-

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bor try

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors try

**Comment by ibacher** [comment]
bors try

**Comment by DilumAluthge** [comment]
Hooray!

**Pull request merged**
