### PR TITLE
Exclude tests that require ENV during pull requests - fix #8

### LINKED ISSUE #8: Exclude tests that require ENV during pull requests
Need to modify travis.yml

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Review by mirestrepo — CHANGES_REQUESTED** [review]
We also need to skip 
```
@testset "Occurrences" begin
    println("-----------------------------------------")
    println("       Testing Occurrences")
    umls_concept = "Disease or Syndrome"
    @time begin
        labels2ind, occur = umls_semantic_occurrences(conn, umls_concept)
    end

    @test length(keys(labels2ind)) > 0
    @test length(find(x->x=="Obesity", collect(keys(labels2ind)))) ==1
end
```

**Comment by mirestrepo** [comment]
Thanks for working on this one!

**Comment by DilumAluthge** [comment]
Happy to do it!

**Comment by DilumAluthge** [comment]
Take a look now - I think I got all of them.

**Comment by DilumAluthge** [comment]
Coverage went down, but that's exactly what we expected, because the whole point is to (selectively) run fewer tests.

**Pull request merged**
