### PR TITLE
Update to umls_semantic_occurrences function

### PR DESCRIPTION
**Pull request by jasonk33**
Added the option to filter by up to 5 different semantic types. Also converted the final object into a dataframe of 1's and 0's with proper column names, ready for use in the apriori function.

### CODE REVIEW

**Review by mirestrepo — CHANGES_REQUESTED** [review]
It will be better to write a function such that it works for any number of semantic types - perhaps it could be an array. The original function can remain intact for the case of only one semantic type. I think the result should still be the bare matrices and have a separate utility function to convert to dataframes

**Comment by jasonk33** [comment]
How many semantic types should it be able to work for, because the way I have it filtering, you need to put each additional semantic type into the or statement, and I'm not sure if that can be done for an arbitrary number. I can add extra cases to the if/elseif statement to allow for even more semantic type filtering, but I think I need a max number, because each different number of filtered has a different line of code attached to it. Do you see what I mean?

**Review by jasonk33 — COMMENTED** [review]
Let me know what you think

**Review by mirestrepo — CHANGES_REQUESTED** [review]
Almost there! - however we need the original call to the function to work as it is used in many other places and we don't want to break it. I know I had suggested arrays but that breaks it for when the function is only called with a string. So either we have two versions of the function or we use variable arguments, define the functions as 
``` function umls_semantic_occurrances{N}(db, umls_semantic_types::Vargarg{String, N})```
then umls_semantic_types  will be a tuple. You will the define filter_mesh_by_concept for vargagrs as well and call it using    
```filter_mesh_by_concept(db, umls_semantic_types...)```
 

Finally the MySQL code can be made more elegant by using the clause IN https://www.tutorialspoint.com/mysql/mysql-in-clause.htm
You would convert  your array to a string ("umps_type1", "umls_type2", ....)  then pass that string to your query

**Comment by jasonk33** [comment]
Made updates you requested, let me know if it is all good to go now

**Comment by mirestrepo** [comment]
Made some changes and merged - feel free to update from master to see what changed

**Pull request merged**
