### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by ibacher**
A few fixes for the tests for this package:

 * Use in-memory SQLite
 * Ensure files are closed in test cases
 * MbedTLS was updated in a way that broke tests using HTTP. This is fixed using a hack.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ibacher Tests are still failing, but I’ve unprotected master so you can merge if you want. We do need to get these tests passing though.

**Comment by DilumAluthge** [comment]
Examples are still failing with:
```
ERROR: LoadError: LoadError: UndefVarError: query not defined
Stacktrace:
 [1] top-level scope at /home/travis/build/bcbi/BioMedQuery.jl/examples/literate_src/1_pubmed_search_and_save.jl:82 [inlined]
```

**Comment by ibacher** [comment]
@DilumAluthge: Thanks. This is going to be a bit iterative, since I don't have a local instance of MySQL to test against...

**Comment by DilumAluthge** [comment]
No worries! That’s what Travis is for :)

**Comment by DilumAluthge** [comment]
Woo hoo!

**Pull request merged**
